service: sls-node-demo

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  endpointType: regional
  profile: admin

functions:
  currentTime:
    handler: function/helloworld.handler
    events:
      - http:
          path: hello
          method: get
