service: sls-node-demo

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  region: cn-northwest-1
  endpointType: regional
  profile: cn

functions:
  currentTime:
    handler: function/helloworld.handler
    events:
      - http:
          path: hello
          method: get
